spring:
  application:
    name: library

  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9000
